name: minor-version-update

on:
  push:
    branches:
      - main
    paths:
      - "powershell/**"
      - "!powershell/Maester.psd1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  CreateRelease:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update PowerShell module version and manifest file
        id: updatemodule
        shell: pwsh
        run: |
          & ./.github/workflows/minor-version-update.ps1

      - uses: actions/checkout@v4
      - name: Update maester.dev command ref docs
        run: ./build/Update-CommandReference.ps1
        shell: pwsh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Update PowerShell module version
